
a.out: main1.o file1.o file2.o file3.o
	gcc -o2 -o a.out main1.o file1.o file2.o file3.o
main1.o: main1.c
	gcc -c main1.c
file1.o: file1.c 
	gcc -c file1.c
file2.o : file2.c
	gcc -c file2.c
file3.o : file3.c
	gcc -c file3.c
#target : source files on which target file is depent 
#taget file will change is source file is change 
#first only changed source file will be compiled then target file will be changed
#gcc -o2 -o something.c Exefilename
